---
# Self-signed ClusterIssuer for PostgreSQL certificates
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-issuer-secret
---
# Create a self-signed Certificate to act as CA
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-issuer-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: PostgreSQL CA
  secretName: ca-issuer-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# Self-signed issuer to bootstrap the CA
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {} 