apiVersion: v1
kind: Secret
metadata:
  name: hippo-s3-backup-secret
  namespace: postgres-operator
type: Opaque
stringData:
  # pgBackRest configuration for S3/MinIO backup
  # These keys are used directly by pgBackRest
  
  # Repository 2 S3 configuration
  repo2-s3-key: "QiOiO8ayHfHY2vLqIbgj"
  repo2-s3-key-secret: "qjAeIi8wh7nsrLw53OzKoelyXidi5ChtfhyNxaec"
  repo2-s3-bucket: "postgresql-backups"
  repo2-s3-endpoint: "http://10.1.21.8:9000"
  repo2-s3-region: "us-east-1"
  
  # Optional: For MinIO with self-signed certificates
  # s3-ca-bundle: |
  #   -----BEGIN CERTIFICATE-----
  #   Your MinIO CA certificate here
  #   -----END CERTIFICATE-----

---
# Example configuration values (commented out)
# For MinIO running locally:
# s3-endpoint: "http://minio.minio.svc.cluster.local:9000"
# 
# For AWS S3:
# s3-endpoint: "s3.amazonaws.com"
# s3-region: "us-west-2"
#
# For Google Cloud Storage (S3 compatible):
# s3-endpoint: "storage.googleapis.com"
#
# For Azure Blob Storage (S3 compatible):
# s3-endpoint: "https://youraccount.blob.core.windows.net" 